site_name: ospsd-team-03
repo_name: ospsd-team-03
repo_url: https://github.com/yawnka/ospsd-team-03

theme:
  name: material

nav:
  - Home: index.md
  - Components:
      - issue_tracker_client_api: components/issue_tracker_client_api.md
      - issue_tracker_client_impl: components/issue_tracker_client_impl.md
  - CircleCI Setup: circleci-setup.md

markdown_extensions:
  - toc:
      permalink: true
