services:
  - type: web
    name: issue-tracker-service
    runtime: docker
    dockerfilePath: ./Dockerfile
    branch: hw-2
    plan: free
    healthCheckPath: /health
    envVars:
      - key: TRELLO_API_KEY
        sync: false
      - key: TRELLO_API_TOKEN
        sync: false
      - key: REDIRECT_URI
        sync: false
